{% set name = "cpprate" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tmaklin/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2a05aa18382bbd1b4158a5d2d8c863bc6b910d4dbb8596fd3d8a4722fed86427

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.1
    - make
    - llvm-openmp        # [osx]
    - libgomp            # [linux64]
  host:
    - libblas
    - eigen
    - bzip2
    - liblzma-devel
  run:
    - bzip2
    - liblzma-devel

test:
  commands:
    - cpprate --help 2>&1 | grep Usage

about:
  home: https://github.com/tmaklin/cpprate
  summary: 'Variable Selection in Black Box Methods with RelATive cEntrality (RATE) Measures'
  description: |
    cpprate is a reimplementation of https://github.com/lorinanthony/rate in C++.
  license: BSD-3-Clause AND MPL-2.0
  license_file:
    - LICENSE
    - external/bs_thread_pool/LICENSE.txt
    - LICENSE_bxzstr
    - LICENSE_cxxargs

extra:
  recipe-maintainers:
    - johnlees
